import os

CHARACTERS = 'ABCDEFGHJKLMNOPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz234567890'
DOMAIN = f'https://{os.getenv("ALLOWED_HOSTS")}/'
MAX_DISPLAY_LENGTH = 50
MAX_EMAIL_LENGTH = 254
MAX_LENGTH = 256
MAX_NAME_LENGTH = 150
PAGE_SIZE = 6
URL_LENGTH = 3
