version: '3'

volumes:
  database:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    env_file: .env
    build: ./backend/
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/static
      - media:/app/media