version: '3'

volumes:
  database:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    env_file: .env
    image: nixaris/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: nixaris/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: nixaris/foodgram_gateway
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend