# Generated by Django 3.2.3 on 2024-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_authentication', '0002_auto_20240902_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='foodgram/images/', verbose_name='Изображение'),
        ),
    ]
