# Generated by Django 3.2.3 on 2024-09-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_authentication', '0006_auto_20240914_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
