# Generated by Django 3.2.3 on 2024-10-16 17:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users_authentication', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscribed'))), name='check_self_subscribe'),
        ),
    ]
