# Generated by Django 3.2.3 on 2024-10-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_authentication', '0009_usersubscription_check_self_subscribe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='check_self_subscribe',
        ),
    ]
