# Generated by Django 3.2.3 on 2024-10-17 16:59

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users_authentication', '0010_remove_usersubscription_check_self_subscribe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscribed')), _negated=True), name='check_self_subscribe'),
        ),
    ]
