# Generated by Django 3.2.3 on 2024-08-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='score',
        ),
    ]
