# Generated by Django 3.2.3 on 2024-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_auto_20240917_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='recepe',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
    ]
