# Generated by Django 3.2.3 on 2024-09-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0008_auto_20240919_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredients', 'ordering': ('name', 'id'), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
