# Generated by Django 3.2.3 on 2024-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0009_alter_ingredient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.CharField(max_length=256, unique=True)),
                ('short_link', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='ingredient_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipetag',
            constraint=models.UniqueConstraint(fields=('recipe', 'tag'), name='tag_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shorturl',
            constraint=models.UniqueConstraint(fields=('full_link', 'short_link'), name='recipe_link'),
        ),
    ]
