# Generated by Django 3.2.3 on 2024-10-06 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0010_auto_20240926_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(related_name='is_favorited', through='foodgram.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shoping_cart',
            field=models.ManyToManyField(related_name='is_in_shoping_cart', through='foodgram.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
