# Generated by Django 3.2.3 on 2024-10-06 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0011_auto_20241006_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shoping_cart',
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(related_name='is_in_shopping_cart', through='foodgram.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Покупки'),
        ),
    ]
