# Generated by Django 3.2.3 on 2024-10-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0012_auto_20241006_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tag', 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
