# Generated by Django 3.2.3 on 2024-10-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0013_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
